# Generated by Django 4.0.2 on 2023-01-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
    ]
